FROM pytorch/pytorch:latest

ENV DEBIAN_FRONTEND noninteractive

EXPOSE 8080

RUN mkdir -p ~/${PROJECT_NAME}
WORKDIR ~/${PROJECT_NAME}

COPY models/vicuna13b/requirements.txt .
RUN pip install -r requirements.txt

COPY infrastructure infrastructure/
COPY models/vicuna13b/ .

ENTRYPOINT ["python3","-m", "server"]